### PR TITLE
Bugs(update testing coverage report): add tests

### PR DESCRIPTION
**Pull request by Aimeana100**
This is a bug fix that for updating coverage report, the previous coverage was 60%.
- added different altelnative tests

### CODE REVIEW

**Comment by Evaristekanova** [comment]
Anathole you still have issues with your tests I am going to merge your PR so that you can present a full package but remember  to fix those issues and after that let me know

**Review by Evaristekanova — APPROVED** [review]

**Comment by Evaristekanova** [comment]
Anathole  some of your tests are failing

**Comment by Aimeana100** [comment]
> Anathole you still have issues with your tests I am going to merge your PR so that you can present a full package but remember to fix those issues and after that let me know

Yes this pull request has not passing the security issues, however i am going to try to resolve it, it is can't break any functionality. it has raised by CodeQL for less codes security.

**Comment by Aimeana100** [comment]
> 



> Anathole some of your tests are failing

Dear sir @Evaristekanova  The failure has been resolved you may now review my codes an approve if no else bugs.

**Comment by Evaristekanova** [comment]
the only problem you had was that tests were not passing but now they are

**Review by Evaristekanova — APPROVED** [review]

**Pull request merged**
